// Regenerates src/api/generated/*.ts from the services' OpenAPI documents, so
// the frontend's types can never drift from the backend's schemas.
//   npm run gen:api        (needs `uv` and the Python workspace)
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import openapiTS, { astToString } from 'openapi-typescript'

const dump = (module) =>
  execFileSync(
    'uv',
    ['run', '--project', '..', 'python', '-c',
     `import json; from ${module}.main import create_app; print(json.dumps(create_app().openapi()))`],
    { env: { ...process.env, REDIS_URL: '', DATABASE_URL: 'sqlite://', NOTIFY_DATABASE_URL: 'sqlite://' } },
  ).toString()

mkdirSync('src/api/generated', { recursive: true })
for (const [module, file] of [['lattice_core', 'core'], ['lattice_notifications', 'notifications']]) {
  const ast = await openapiTS(JSON.parse(dump(module)))
  writeFileSync(`src/api/generated/${file}.ts`,
    '/* eslint-disable */\n// Generated by scripts/gen-api.mjs — do not edit.\n' + astToString(ast))
  console.log(`wrote src/api/generated/${file}.ts`)
}
